### PR TITLE
Some cleanups and release v0.13.0

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by RCasatta** [comment]
commit 715ecabab8126bcbaf3e9c118ddad47d7f1a7fd9 desription is recursive :)

**Comment by stevenroose** [comment]
There was a mistake in the README, still mentioning 1.22, but other than that, I don't see what you mean?

**Comment by RCasatta** [comment]
It is: "Add MSRV section to MSRV" I think you mean "Add MSRV section to Readme"

**Comment by stevenroose** [comment]
oooh

**Comment by stevenroose** [comment]
fixed!

**Comment by RCasatta** [comment]
ack 23cb44cd146aa2834fc38ab16fa53eedafde2c18

**Review by apoelstra — APPROVED** [review]
utACK 6f1bd1b97eb17523f71a7dbc0a25acb56d831f7f

**Pull request merged**
