### PR TITLE
Make TxOut generic in Prevouts

### PR DESCRIPTION
**Pull request by uncomputable**
Useful when prevouts are saved in a vector.

### CODE REVIEW

**Comment by sanket1729** [comment]
I guess MSRV broke :(

**Comment by uncomputable** [comment]
`cargo +1.41.1 test --verbose --features=serde` seems to be broken. Since this is the only feature currently tested, I suggest bumping the Rust version to something like 1.58 for the single serde test. `integration` seems to be broken, too. I can make a PR.

**Comment by RCasatta** [comment]
Didn't look the details but recently serde upgraded syn which broke MSRV in another repo of mine.
If it's the case I think adding `cargo update -p serde --precise 1.0.152` in the CI with toolchain `1.41.1` is more appropriate

**Comment by uncomputable** [comment]
@RCasatta Thanks for pointing this out. @apoelstra did something along these lines in #162. CI seems to be working now.

**Comment by apoelstra** [comment]
dc6f5202ed276511cee002cd5942c28cd58a9f32 looks good. Verified that it is essentially the same as 10fedfb3b44edef1aa69c16452fd27bb8cf65309 in rust-bitcoin.

**Review by apoelstra — APPROVED** [review]
ACK dc6f5202ed276511cee002cd5942c28cd58a9f32

**Pull request merged**
