### PR TITLE
Release v0.19.1

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by stevenroose** [comment]
https://github.com/ElementsProject/rust-elements/pull/131/files is also non-breaking so I'd be ok to have this in too before we do the 2018 break.

**Comment by delta1** [comment]
ACK e596aacc19fb3914f32ae42b64bcc5a970388075

**Review by apoelstra — APPROVED** [review]
ACK e596aacc19fb3914f32ae42b64bcc5a970388075

**Comment by apoelstra** [comment]
Tagged and released.

**Pull request merged**
