### PR TITLE
update `rust-bitcoin` to 0.18

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by instagibbs** [comment]
this PR increases expected numbers :)

**Comment by apoelstra** [comment]
Lol, not enough of them.

**Comment by apoelstra** [comment]
Updated fuzztests `bitcoin` version too.

**Comment by stevenroose** [comment]
I'm not part of the repo apparently :p

**Comment by instagibbs** [comment]
ACK this PR with 50% more version changes!

**Comment by apoelstra** [comment]
Thanks! And I added Steven as a collaborator on this repo.

**Pull request merged**
