### PR TITLE
Add support for hashing JSON asset contract

### PR DESCRIPTION
**Pull request by stevenroose**
Annoyingly this takes 2 extra dependencies. I made them optional, but default.

### CODE REVIEW

**Comment by RCasatta** [comment]
You can use std collection `BTreeMap` to avoid using IndexMap dep

**Comment by stevenroose** [comment]
@RCasatta hmm, because the BTreeMap is automatically ordered. Hmm. Yeah I used indexmap because that's what serde_json uses internally for maps which "preserve order". But perhaps if the order needs to be lexicographic anyway, a BTreeMap would make sense. I don't know the algorithm, but it would do some sorting/comparing on every insert, though. But I suppose to be able to drop a dependency, that would make sense.

**Comment by stevenroose** [comment]
Hmm, I'm confused now. I was quite sure that both our methods would break if I introduced new fields in a nested object. Like `{"entity":{"domain":"xxx","author":"yyy"}}`. But somehow it doesn't; I'm not sure if I'm just lucky.

**Comment by stevenroose** [comment]
Thanks for the suggestion, btw! It seems that serializing into a BTreeMap somehow magically also orders nested objects...

**Comment by stevenroose** [comment]
Cool, you can see here that serde's default implementation for `BTreeMap` works recursively. I'm impressed :)

**Comment by RCasatta** [comment]
ack 94ba7f6

**Pull request merged**
