### PR TITLE
Add PeginData::mainchain_tx inspector

### PR DESCRIPTION
**Pull request by stevenroose**
Just a nice utility for the mainchain tx.

### CODE REVIEW

**Comment by apoelstra** [comment]
If you add a commit to do a point release we could get this out in 0.21.1.

**Review by sanket1729 — APPROVED** [review]
utACK ad26068e7a5ec7da19d485c30bb6f5efe60bcab3

**Comment by stevenroose** [comment]
Ok, I'll also add the same getter for the merkle proof because I need it too :)

**Comment by stevenroose** [comment]
I changed the name, so sanket's ack is void, sorry. Also added extra commit and point release.

I based the conclusion that the merkle_proof is a merkleblock based on the fact that we fill with with `gettxoutproof` output and that one has
```cpp
    CDataStream ssMB(SER_NETWORK, PROTOCOL_VERSION | SERIALIZE_TRANSACTION_NO_WITNESS);
    CMerkleBlock mb(block, setTxids);
    ssMB << mb;
    std::string strHex = HexStr(ssMB);
    return strHex;
```

**Review by sanket1729 — APPROVED** [review]
utACK 72afb4740e26c9cd658a0d544e7579f329f2b808. Looks good, but would be good to have some fixed test vector here.

**Review by apoelstra — APPROVED** [review]
ACK 72afb4740e26c9cd658a0d544e7579f329f2b808

**Comment by apoelstra** [comment]
@stevenroose yep, it's a merkleblock -- as you noticed, we ask users to generate this using `gettxoutproof` (well, I think we do this automatically usually).

I would also like a fixed test vector but I don't think we need to hold up the PR or release for it. I'd be okay doing a 0.20.2 "bugfix" release on the off chance that this is somehow broken.

**Comment by apoelstra** [comment]
Tagged & published

**Pull request merged**
