### PR TITLE
Add BlockHeader::clear_witness and ::is_dynafed methods

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by stevenroose** [comment]
Fixed for 1.22.

**Comment by stevenroose** [comment]
Those matches over complex enum variants are super painful and inflated line-wise. I think we would have better have had 2 structs and simpler tuple variants taking that one struct instead of the variant taking fields. 
It's basically a PITA when you're actually using these variants to get any fields from them once you know which variant is chosen. Same goes for https://github.com/ElementsProject/rust-elements/pull/34.

So just some simple utilities to save lines and improve readability of code using these enums.

**Comment by jonasnick** [comment]
Sorry, should have been more specific. I get that it's more concise but I was wondering where `clear_witness` is useful.

**Comment by instagibbs** [comment]
@jonasnick witness-stripped blockheaders for when you don't need witness data to persist after witness is validated

**Comment by apoelstra** [comment]
Needs rebase.

**Comment by stevenroose** [comment]
Those matches over complex enum variants are super painful and inflated line-wise. I think we would have better have had 2 structs and simpler tuple variants taking that one struct instead of the variant taking fields. 
It's basically a PITA when you're actually using these variants to get any fields from them once you know which variant is chosen. Same goes for https://github.com/ElementsProject/rust-elements/pull/34.

So just some simple utilities to save lines and improve readability of code using these enums.

**Pull request merged**
