### PR TITLE
Fix and export ContractHash

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by stevenroose** [comment]
Heh, I force pushed another commit but GitHub is not showing it.

**Comment by shesek** [comment]
Wasn't ContractHash using sha256d to get reverse serialization that matches cpp-elements?

**Comment by stevenroose** [comment]
Yeah it it's not a double hash. So then I fixed that with the macro that allows creating a hash newtype but changing the reversed-ness :) It's messy, but well. It's more important that `ContractHash::hash` does the right thing.

**Comment by shesek** [comment]
Ah, nice! This is of course better. :) I guess this what the last `true` macro argument signifies?

**Comment by stevenroose** [comment]
Yeah. It's a but bad that it's just a boolean, right? Perhaps I should make that a `reverse: $rev:expr` instead in the macro definition...

**Pull request merged**
