### PR TITLE
transaction: range-check pegin data when parsing

### PR DESCRIPTION
**Pull request by apoelstra**
It is possible to cause a panic by calling `TxIn::pegin_data` on a malformed pegin, which has 6 entries and the last one (which should be a Merkle proof of block inclusion) is too small to even have a blockhash in it.

On the actual chain this should not be possible because invalid pegin data would be rejected.

### CODE REVIEW

**Comment by apoelstra** [comment]
CI failure is an unrelated thing; I have another branch I'm working on to fix clippy and update things but I'm seeing a weird bug with clippy.

**Review by delta1 — APPROVED** [review]
ACK f86e219086e25288e4508b02996c8058e3b36496

**Comment by apoelstra** [comment]
Rebased. Ready for re-review.

**Comment by delta1** [comment]
reACK [639c964](https://github.com/ElementsProject/rust-elements/pull/203/commits/639c964f91894bf5f22d7a3fe9ac504ab31a3c7d)

**Pull request merged**
