### PR TITLE
Add Block::get_size() and Block::get_weight()

### PR DESCRIPTION
**Pull request by shesek**
Similarly to https://github.com/rust-bitcoin/rust-bitcoin/pull/417.

Unlike https://github.com/rust-bitcoin/rust-bitcoin/pull/417, this doesn't avoid serialization entirely and still serializes the header in order to determine its size. This could be avoided too, but most of the performance gain is already achieved by not serializing transactions, which seemed good enough.

### CODE REVIEW

**Comment by shesek** [comment]
I also verified the weight and size to match what cpp-elements reports for the [liquid mainnet block at height 2](https://blockstream.info/liquid/block/57f26b5a65e461e8aa690e97595702605ef4fff5308d9507121b44e035663dcd).

**Comment by stevenroose** [comment]
This needs a rebase.

**Comment by shesek** [comment]
@stevenroose rebased.

**Comment by stevenroose** [comment]
closing and reopening to try to get Travis to do something

**Comment by stevenroose** [comment]
@jonasnick @apoelstra can any of you merge this? I checked Travis manually and all jobs passed, is just that the reporting back to Github seems broken

**Pull request merged**
